### ISSUE TITLE
Cannot use v3 in Angular 17 project

### ISSUE THREAD

**Issue by iTchTheRightSpot** [Flutterwave/Angular-v3#24]
Have you read our [Code of Conduct](https://github.com/Flutterwave/Angular/blob/master/CONTRIBUTING.md)? By filing an Issue, you are expected to comply with it, including treating everyone with respect

Do you want to ask a question? Are you looking for support? The developer slack is the best place for getting [support](https://bit.ly/34Vkzcg)

### Description

I am following Using Flutterwave as a Component Method 2 in the readme. My project is using Angular 17. After following the instructions (NB: If you experience compilation errors in your app after importing the Flutterwave module, component or service. Kindly include the following line in tsconfig.app.json under compilerOptions :) I get the error `Error: src/app/store-front/payment/payment/payment.component.ts:8:27 - error NG2012: Component imports must be standalone components, directives, pipes, or must be NgModules.`. I followed the readme 

<img width="1441" alt="image" src="https://github.com/Flutterwave/Angular-v3/assets/80619808/f1f08502-4d8b-4dfa-a6d3-953ba48505e9">

### Steps to Reproduce

1. Import FlutterwaveModule to the choice of standalone component.
2. Run ng serve and error would be reproduced

**Expected behaviour:**

Display component button

**Actual behaviour:**

<img width="1061" alt="image" src="https://github.com/Flutterwave/Angular-v3/assets/80619808/80397c9b-db3c-4c2e-a047-b127dfa35195">

### Configuration

- API Version: v3
- Environment: 
- Browser: 
- Language:

**Comment by jmmwangi007** [comment]
Was this ever fixed?

**Comment by iTchTheRightSpot** [comment]
> Was this ever fixed?

Ended up using another provider

**Comment by jmmwangi007** [comment]
Probably not the best place to ask this, but what did you switch to? Paystack?
